include:
  - project: nudchannel/ci/gitlab-ci-templates
    ref: buildkit
    file:
      - build/default.gitlab-ci.yml
      - client/typescript.gitlab-ci.yml
      - deploy/default.gitlab-ci.yml
      - lint/default.gitlab-ci.yml
      - node/node.gitlab-ci.yml
      - node/test-coverage.gitlab-ci.yml
      - release/default.gitlab-ci.yml
      - rules/test.yml
  - local: .gitlab/ci/*.gitlab-ci.yml

stages:
  - lint
  - build
  - test
  - release
  - deploy

default:
  interruptible: true

.node:
  image: node:24-alpine
  variables:
    PNPM_VERSION: 9

lint:
  stage: lint
  needs: []

publish:
  stage: release

deploy:
  needs:
    - job: build:image
      optional: true
