version: '3.5'

services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nudchannel
    volumes:
      - ${PGDATA_VOLUME-pgdata}:/var/lib/postgresql/data
  mongodb:
    image: ${NUDCH_IMAGE_REGISTRY-registry.nas.nudchannel.com:7171}/nudchannel/database/devdb
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  webdav:
    image: ${NUDCH_IMAGE_REGISTRY-registry.nas.nudchannel.com:7171}/nudchannel/ci/mock-webdav
    ports:
      - 8080:80
  minio:
    image: ${NUDCH_IMAGE_REGISTRY-registry.nas.nudchannel.com:7171}/nudchannel/ci/minio
    ports:
      - 9000:9000
      - 9001:9001 # root:password

volumes:
  pgdata:
