services:
  tracing:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
    ports:
      - 16686:16686 # webui
      - 4317:4317 # otlp grpc
      - 4318:4318 # otlp http
