version: '3.5'

services:
  mongodb:
    image: ${NUDCH_IMAGE_REGISTRY-registry.nas.nudchannel.com:7171}/nudchannel/database/devdb
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  webdav:
    image: ${NUDCH_IMAGE_REGISTRY-registry.nas.nudchannel.com:7171}/nudchannel/ci/mock-webdav
    ports:
      - 8080:80
  minio:
    image: ${NUDCH_IMAGE_REGISTRY-registry.nas.nudchannel.com:7171}/nudchannel/ci/minio
    ports:
      - 9000:9000
      - 9001:9001 # root:password
  photo-processor:
    image: ${NUDCH_IMAGE_REGISTRY-registry.nas.nudchannel.com:7171}/nudchannel/api/photo-processor
    ports:
      - 4001:4001
    environment:
      PORT: 4001
      RABBITMQ_URI: amqp://guest:guest@rabbitmq
      WEBDAV_URL: http://webdav
      MINIO_ENDPOINT: minio
      MINIO_ACCESS_KEY: ci-access-key
      MINIO_SECRET_KEY: ci-secret-key
      MINIO_BUCKET_NAME: nudch-photos
