export enum Config {
  HTTP_PORT = 'http.port',
  HTTP_SWAGGER_PATH = 'http.swagger.path',
  LOG_LEVEL = 'log.level',
  LOG_BUFFER = 'log.buffer',
  DATABASE_MONGODB_PREFIX = 'database.mongodb.',
  REDIS_DEFAULT_HOST = 'database.redis.default.host',
  REDIS_DEFAULT_PORT = 'database.redis.default.port',
  REDIS_DEFAULT_PASS = 'database.redis.default.pass',
  REDIS_DEFAULT_DB = 'database.redis.default.db',
  GAPIS_CLIENT_ID = 'googleapis.clientId',
  GAPIS_CLIENT_SECRET = 'googleapis.clientSecret',
  GAPIS_CALLBACK = 'googleapis.callback',
  GAPIS_EMAIL = 'googleapis.email',
  GAPIS_SERVICE_EMAIL = 'googleapis.service.email',
  GAPIS_SERVICE_PRIVATEKEY = 'googleapis.service.privateKey',
  NUDCH_TOKEN_ISSUER = 'authentication.accessToken.issuer',
  NUDCH_TOKEN_PUBLIC_KEY = 'authentication.accessToken.publicKey',
  NUDCH_TOKEN_PRIVATE_KEY = 'authentication.accessToken.privateKey',
  NUDCH_TOKEN_SECURE = 'authentication.refreshToken.secure',
  DELIVERY_UPCOMINGEVENT_CRON = 'delivery.upcomingEvent.cron',
  DELIVERY_UPCOMINGEVENT_LOOKAHEADHOUR = 'delivery.upcomingEvent.lookAheadHour',
  DELIVERY_UPCOMINGEVENT_RANGEHOUR = 'delivery.upcomingEvent.rangeHour',
  DELIVERY_UPCOMINGEVENT_DISCORDWEBHOOK = 'delivery.upcomingEvent.discordWebhook',
}
