export enum ServiceProvider {
  DISCORD_REST = 'DISCORD_REST',
  DISCORD_OAUTH2_API = 'DISCORD_OAUTH2_API',
  GOOGLE_OAUTH2 = 'GOOGLE_OAUTH2',
  GOOGLE_OAUTH2_CLIENT = 'GOOGLE_OAUTH2_CLIENT',
  LDAP_SERVER = 'LDAP_SERVER',
}
