export const GALLERY_ID_LENGTH = 7
export const GALLERY_TITLE_LENGTH = 255
export const GALLERY_TAG_LENGTH = 63
export const YOUTUBE_ID_LENGTH = 11
export const MINIMUM_PHOTO_RESOLUTION_MP = 5
export const GALLERY_REPORT_TITLE_LENGTH = 255
