http:
  port: PORT

log:
  level: LOG_LEVEL
  buffer: BUFFER
  loki:
    url: LOG_LOKI_URL

processor:
  enabled: PROCESSOR_ENABLED

rabbitmq:
  uri: RABBITMQ_URI
  wait:
    enabled: RABBITMQ_WAIT_ENABLED
    timeout: RABBITMQ_WAIT_TIMEOUT

authentication:
  accessToken:
    publicKey: NUDCH_PUBLIC_KEY
    privateKey: NUDCH_PRIVATE_KEY

photoProcessor:
  url: PHOTO_PROCESSOR_URL

delivery:
  smtp:
    host: DELIVERY_SMTP_HOST
    port: DELIVERY_SMTP_PORT
    secure: DELIVERY_SMTP_SECURE
    username: DELIVERY_SMTP_USERNAME
    password: DELIVERY_SMTP_PASSWORD
