http:
  port: 4000
  swagger:
    path: swagger
    authGroups: []
  bullboard:
    path: bullboard
    authGroups: []
  baseUrl:
    photo: https://photos.nudchannel.com

log:
  level: info
  buffer: true
  loki:
    url: ""

otlp:
  enabled: false
  trace:
    url: ""
  metric:
    url: ""
    intervalMillis: 15000

processor:
  enabled: false

database:
  mongodb:
    default: ""
    accounts: ""
    gallery: ""
    mailer: ""
    audit: ""
  redis:
    default:
      host: ""
      pass: ""
      port: 6379
      db: 0

rabbitmq:
  uri:
  wait:
    enabled: false
    timeout: 5000

googleapis:
  clientId: ""
  clientSecret: ""
  callback: ""
  email: ""
  service:
    email: ""
    privateKey: ""

photoProcessor:
  url: ""

authentication:
  accessToken:
    issuer: accounts.nudchannel.com
    publicKey: ""
    privateKey: ""
  refreshToken:
    secure: true

auditLog:
  enabled: false

delivery:
  upcomingEvents:
    cron: ""
    lookAheadHours: 9
    rangeHours: 12
    discordWebhook: ""
  startingEvents:
    cron: ""
    rangeMinutes: 15
    discordWebhook: ""
  smtp:
    host:
    port:
    secure:
    username:
    password:
