http:
  port: 4000
  swagger:
    path: "swagger"

log:
  level: info
  buffer: true

database:
  mongodb:
    default: ""
    accounts: ""
    gallery: ""
    mailer: ""
  redis:
    default:
      host: ""
      pass: ""
      port: 6379
      db: 0

googleapis:
  clientId: ""
  clientSecret: ""
  callback: ""
  email: ""
  service:
    email: ""
    privateKey: ""

authentication:
  accessToken:
    issuer: accounts.nudchannel.com
    publicKey: ""
    privateKey: ""
  refreshToken:
    secure: true

delivery:
  upcomingEvent:
    cron: 0 9,21 * * *
    lookAheadHour: 9
    rangeHour: 12
    discordWebhook: ""
