runMode: server

http:
  port: 4000
  secondaryPort: 5000
  swagger:
    path: swagger
    authGroups: []
  bullboard:
    path: bullboard
    authGroups: []
  baseUrl:
    accounts: https://accounts.nudchannel.com
    photo: https://photos.nudchannel.com

log:
  level: info
  buffer: true
  loki:
    url: ""

otlp:
  enabled: false
  trace:
    url: ""
  metric:
    url: ""
    intervalMillis: 15000

database:
  mongodb:
    default: ""
    accounts: ""
    gallery: ""
    photo: ""
    mailer: ""
    audit: ""
  redis:
    default:
      host: ""
      pass: ""
      port: 6379
      db: 0

rabbitmq:
  uri:
  wait:
    enabled: false
    timeout: 5000
  default:
    prefetchCount: 1

storage:
  webdav:
    url: http://localhost:4000
    authtype: password
    username: ""
    password: ""

googleapis:
  clientId: ""
  clientSecret: ""
  callback: ""
  email: ""
  service:
    email: ""
    privateKey: ""

discord:
  clientId: ""
  clientSecret: ""

photo:
  minio:
    endpoint: ""
    port: 9000
    access_key: ""
    secret_key: ""
    use_ssl: false
    bucket_name: ""
  stream:
    upload: false
    cache:
      max-age: 2592000 # 30 days
      s-maxage: 3600 # 1 hour
      stale-while-revalidate: 86400 # 1 day
  processor:
    default:
      quality: 80
    watermark:
      "01":
        file: assets/watermarks/01.png
        position: bottom-left
        size: 0.01
        marginX: 0
        marginY: 0.01
        opacity: 0.75

authentication:
  accessToken:
    issuer: accounts.nudchannel.com
    publicKey: ""
    privateKey: ""
  refreshToken:
    secure: true

auditLog:
  enabled: false

delivery:
  upcomingEvents:
    cron: ""
    lookAheadHours: 9
    rangeHours: 12
    discordWebhook: ""
  startingEvents:
    cron: ""
    rangeMinutes: 15
    discordWebhook: ""
  smtp:
    host:
    port:
    secure:
    username:
    password:
