log:
  level: debug
  buffer: false
  loki:
    url: http://nudch-wireproxy-cftunnel.nudch-internal.svc:3100

http:
  baseUrl:
    accounts: http://webservice.dev.nudchannel.com

ldap:
  root_secret: secret

otlp:
  metric:
    url: http://prometheus-server.nudch-internal.svc/api/v1/otlp/v1/metrics

database:
  postgres:
    host: postgres
    user: nudchannel
    pass: nudchDev!123
    port: 5432
    db: nudchannel
  mongodb:
    default: mongodb://root:nudchDev!123@mongodb/main?authSource=admin
    accounts: mongodb://root:nudchDev!123@mongodb/accounts?authSource=admin
    gallery: mongodb://root:nudchDev!123@mongodb/gallery?authSource=admin
    photo: mongodb://root:nudchDev!123@mongodb/photo?authSource=admin
    mailer: mongodb://root:nudchDev!123@mongodb/mailer?authSource=admin
  redis:
    default:
      host: redis-master
      pass: nudchDev!123
      port: 6379
      db: 15

rabbitmq:
  uri: amqp://dev:nudchDev!123@rabbitmq.nudch-prod/dev

authentication:
  accessToken:
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz0Qx2z/NTkZFmC0p4BmJ
      L02ZG1xsUDoidllghcx7GkqTOQIeepP3QoJoFlDG1iVerhtb98sUQB4SrXKdjyc+
      EhcIt53Cfn2IJvo9IrlxkCR3fyhGmrsblb+wNvC4QBh+3FC9Mqx+1EHSpAJLIYVz
      BDOwLBv7K4TmHtTRHI3ZkDPR4WgRD4tJTKMILtLeIb9K6bBWSMTTkb6X2xxdlzzC
      Z5X8o5TANUOK3JMZp1uZI/DaDJt/4tomNJahpnnqi0/9qkxIlQcm5111EGSRVkan
      cCIwf1wsgSF+ykeoJIN82AaozC3HIbV0NKGDKcv+tFhgtS3OiG9MwYfm0v0NUuEu
      XwIDAQAB
      -----END PUBLIC KEY-----
    privateKey: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDPRDHbP81ORkWY
      LSngGYkvTZkbXGxQOiJ2WWCFzHsaSpM5Ah56k/dCgmgWUMbWJV6uG1v3yxRAHhKt
      cp2PJz4SFwi3ncJ+fYgm+j0iuXGQJHd/KEaauxuVv7A28LhAGH7cUL0yrH7UQdKk
      AkshhXMEM7AsG/srhOYe1NEcjdmQM9HhaBEPi0lMowgu0t4hv0rpsFZIxNORvpfb
      HF2XPMJnlfyjlMA1Q4rckxmnW5kj8NoMm3/i2iY0lqGmeeqLT/2qTEiVBybnXXUQ
      ZJFWRqdwIjB/XCyBIX7KR6gkg3zYBqjMLcchtXQ0oYMpy/60WGC1Lc6Ib0zBh+bS
      /Q1S4S5fAgMBAAECggEALNBX30nqQBRdk8ugFD4xNTMX+ZyAJtCLBv/IKOXPcB3T
      uy3EHUjE23KKwthwRXkLAaYUun0EQeC+tRXlD0Cy4QJt9hV8KhFGUPcmJM3nyfy4
      gZvZuDbgff5WQWrGy8UAGO60GbLGMWqR+rgsOnE6Lxxl6QObyQsRHnVxSTU6Zz0J
      PYN1klkXzjyeN3aRRMI1rTuQt9V8H7QPo6Wgb719pqQZZ8vVrwk3UM9DikcFz7CV
      kMolWBYzOc2mKbWsE4mo7nCzTui25iasIdy6z+KCifiIV8gwzChodo0/PiS3yOFo
      cNlsT8Q9ULsDLaz5rOfUlLg9slOhzS9oAaX1XdE4MQKBgQD2MHpvqQPZYFYqS7m+
      xxwB+d88Ux1DeGdHaMVti2ttF4AeqwPHiRufXCFB7pKLf7xB1s2TdrKSfic1jC2a
      f0KRO8XOEQ3dkvbnyJdhbBr2B9RlM79xF40ipq7NeBS4eJ8Q+DDubLYfgSipoaG9
      Cd3Cybjtgdrd1sZzo7Bg/j6WbQKBgQDXhqPvtBgJkj/+zXDEYlfwvztnlVt33l6E
      OuOjBdIs4MPhlgvU9Snv35JR0omsywE6NErCbp6uxqScNPeMnqXAHPsC0KWbTJFK
      raTZ1emZQxqf5PMdZd9Jsa0OWrOHY1JSvN1/nlUN3Q4LDq8qCY2PRq09C51IkMNz
      q+v2u1mIewKBgHpTlEKvRI5aY/YYMm8tGCmTMu0Sj1PbG9ZLpO3NfM90AeE7MGGR
      KvyAFrZgCMjv62b7iKJhNFG+BVWCFZbS7QylGqBNsQoL4EtDTJTH1o2xTkQK9nEH
      NsWk9O57YDBZHxCbghS2R7hXwRCok2kO4fXLreu1vj7EXU9QYm+PZSHxAoGAVAOl
      JgyTDjAXiDD3U2Zul2dENeWv6TMirvLxx5u+SUY4tVgzNol3Fo2VURX8GwJrcQ/v
      UImki8bdZhLzqLozLIdfhcJlu/sF7BFyYIQVcmwJFek+p+gNOYHsTtsmfpFGBwCe
      a2ACEcxo7ACGYaGlsANCBrjfT+k2d4G+EskHZr8CgYEA0ctodUZm+/loDaHe0ojT
      5t70R59f2nmX4IR07NRz0+8OvpSX7duSihBLfkCu5XVxZMGDQsiOMqrRRkTX8ncZ
      tViQhduA9T4EaTNMvj88RFZStvesM9v3Sg+0hTQ+sapjkHghoXM03oalqA8J/BnN
      ccOIb5DqYZIF9L/MqLqfDK4=
      -----END PRIVATE KEY-----
  refreshToken:
    secure: false

googleapis:
  clientId: 1083281018269-fvqevf7hgj2svu0m431anvq5ldofud8d.apps.googleusercontent.com
  clientSecret: ''
  service:
    email: dev-85@nudchannel.iam.gserviceaccount.com
    privateKey: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDOTI47cdivt2JS
      0vU72qEI3S+QaeC+s54ar64dprfd4iqzjzx7h33vQ1sGWNH0HRZFZKnfHaWwh8z7
      TkVXlAI0lnwIwsrt93plvTyFozUzfP7F8xRVXHTr71vCU8l7n/NzKThbwqLo6UBX
      ZBBFpzG72ffMMX1/1Pho4pvJn3ZCgkiCwxmUo9rq6bUqAHtBSSWMUmyZKEnhufII
      PhDeUcepU5bsWp0CKrMv+D3iLoQpoPyrNpvsDTVbWduOTnmYQTTDBy3FA4O/LarP
      pwwayb4vkEfpJ5KxiOae15j0Jbp56/zqhQghlylzKplwCqCkll/CrszU0C1csmHp
      QwYfI2nZAgMBAAECggEAFsWSTys/UBEh7jLJXVqiGy6AJzSauW4uAfPZuD3sjpZe
      II0rb9bKTsh8chhIj6XMzSriCeX1wcVRuf0/L/4/WpLwXM60s/0U8olHlphIAXeX
      D15oRI5kvRziH/Kb+1SR/MikZxOWZDeIEcVyut+MYLgcD1r4p41IgNpfuCstFITm
      YSVhC7ChaqDzMankakLcqDTzKBCUfON/WftOGmQ0TIXgRAoHGaAf6iMLpgoPVQI1
      VYOeaCsGupiiVUe30yErIToi9eAJlbcZGNu+ks5TgbttXic5zBt2SZ6IoYwHB6QP
      0ggoX7PYzVcrHVr6Zj56vwvGMh7ZfEHXDoZxJNo0MQKBgQD7IkAwDn/Y0UFCdgev
      Ku01HsK+4hS/AKqvTBqQymzEH5m8vWwyKrqVCj98SOLEkgvh+kYEYLk6y/PwHaVT
      dfd789mLsSdpcKLQIJE+SVuwhDFojjji7/ehnZF5zBZwmUxOk8Q6gWLz57P3gJIO
      e2U4u1Q+nTxbyiX2Qoo2pqfd8QKBgQDSS+bu/Sy22iMbyniWt5FEYPWa04z93lt9
      qAmKUwrJu5cQjiiPHhTxqzpnGavQL8QxfsQV8aC2ScuMFO3i2E43QPMWDm2FiUi+
      PhRpuesRSklSelKOo5bWh7bU+e9W6XICjLzwwM95HZpZbMfKdaJOLhbjzml6T6ZK
      ireHzeWCaQKBgActXmpBL9Qxfsz4dJXEA01+WJB+A5vF2Br0cNnsfxlH0ev7+eih
      If36cgAKUTjO97n4niGn5gNRKuKU5lGxUGZhfLkqUfcIeg66r4v5Kr6ruIHFdsi9
      lPUwfKTfeVC0gOLKBFSrt/lCiPks2n/BdQ4fBHRZqAzzhQw5sJuJPcjxAoGBAKmK
      j+/1JOt2CgAJyBaaf/9EvD3KeEzjy5cOtkJSmMvy9ONf+MsJUZFUno0oYSBCokXV
      EXkviIXuELAq326XPNfHATOzBhE2kPLvUb27KgySe3KHM6/Tq3PhjkE+Dvte0Y/E
      rz7Z82qNtzaJQLm1BNlKxyF59Aer10EZfMV79aChAoGASA6HsxuS/U5YdGZqH0DO
      4ldc98k4i/+gIt/NFwba6NsV70PM3Aw98DknvZfv6+552aLwpjYSM6cR20uAh2s5
      XimmFWAjJ0TkhqmO0HqWQ9K6SiEgMVEPp0yxEQfgXh486TN4COfrmVSwvTLWShYu
      FS8ORJ96zn4FvIZVOP0cnWk=
      -----END PRIVATE KEY-----

discord:
  clientId: '1095379875226988664'
  clientSecret: ''

photo:
  minio:
    endpoint: storage.nas.nudchannel.com
    port: 7171
    access_key: nudch-dev
    secret_key: ab6NuBi^GNhx*7ou
    use_ssl: true
    bucket_name: nudch-photos-storage-dev
