node_modules:
  allow_failure: false

build:
  needs: []

build:openapi:
  extends:
    - build:node
  variables:
    RUN_MODE: server
  script: npm run generate:openapi
  artifacts:
    paths:
      - openapi.json
      - openapi.yaml

client:
  needs:
    - build:openapi
  variables:
    OPENAPI_SPECFILE: ./openapi.json
