build:
  needs: []

build:openapi:
  extends:
    - build:node
  script: npm run generate:openapi
  artifacts:
    paths:
      - openapi.json
      - openapi.yaml

client:
  needs:
    - build:openapi
  variables:
    OPENAPI_SPECFILE: ./openapi.json
