node_modules:
  rules:
    - when: never

build:
  needs: []

build:node:
  variables:
    VERSION_SUFFIX: -$CI_PIPELINE_ID
  script:
    - export APP_VERSION=$(node -p "require('./package.json').version")$VERSION_SUFFIX
    - pnpm run build
    - rm -rf node_modules/
    - pnpm install --frozen-lockfile --prod
    - npm version $APP_VERSION --allow-same-version --no-git-tag-version
    - echo "APP_VERSION=$APP_VERSION" > .env
  artifacts:
    paths:
      - dist
      - node_modules/**
      - .env

build:openapi:
  extends:
    - build:node
  script: npm run generate:openapi
  artifacts:
    paths:
      - openapi.json
      - openapi.yaml

client:
  needs:
    - build:openapi
  variables:
    OPENAPI_SPECFILE: ./openapi.json
