node_modules:
  before_script:
    - npm i -g pnpm@$PNPM_VERSION
    - pnpm i --frozen-lockfile --prefer-offline --prod
  allow_failure: false

build:
  needs: []

build:openapi:
  extends:
    - build:node
  script: npm run generate:openapi
  artifacts:
    paths:
      - openapi.json
      - openapi.yaml

client:
  needs:
    - build:openapi
  variables:
    OPENAPI_SPECFILE: ./openapi.json
