.use-dependencies:
  variables:
    FF_NETWORK_PER_BUILD: 1
  services:
    - &rabbitmq
      name: docker.io/rabbitmq:3.13
      alias: rabbitmq
    - &mongodb
      name: $NUDCH_IMAGE_REGISTRY/nudchannel/database/devdb
      alias: mongodb
      variables:
        NODE_OPTIONS: ""
    - &redis
      name: docker.io/redis:7-alpine
      alias: redis
    - &webdav
      name: $NUDCH_IMAGE_REGISTRY/nudchannel/ci/mock-webdav
      alias: webdav
    - &minio
      name: $NUDCH_IMAGE_REGISTRY/nudchannel/ci/minio
      alias: minio
  tags:
    - medium
    - docker

.use-app:
  variables:
    FF_NETWORK_PER_BUILD: 1
  services:
    - <<: *rabbitmq
    - <<: *mongodb
    - <<: *redis
    - <<: *webdav
    - <<: *minio
    - name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      alias: webservice-worker
      variables:
        NODE_ENV: test
        NODE_APP_INSTANCE: worker
    - name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      alias: webservice
      variables:
        NODE_ENV: test
        NODE_APP_INSTANCE: server
  tags:
    - medium
    - docker
