.use-dependencies:
  variables:
    FF_NETWORK_PER_BUILD: 1
  services:
    - &rabbitmq
      name: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/rabbitmq:3.13
      alias: rabbitmq
    - &mongodb
      name: $NUDCH_IMAGE_REGISTRY/nudchannel/database/devdb
      alias: mongodb
    - &redis
      name: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/redis:7-alpine
      alias: redis
    - name: $NUDCH_IMAGE_REGISTRY/nudchannel/ci/mock-webdav
      alias: webdav
    - name: $NUDCH_IMAGE_REGISTRY/nudchannel/ci/minio
      alias: minio
    - name: $NUDCH_IMAGE_REGISTRY/nudchannel/api/photo-processor
      alias: photo-processor
      variables:
        PORT: 4001
        RABBITMQ_URI: amqp://guest:guest@rabbitmq
        WEBDAV_URL: http://webdav
        MINIO_ENDPOINT: minio
        MINIO_ACCESS_KEY: ci-access-key
        MINIO_SECRET_KEY: ci-secret-key
        MINIO_BUCKET_NAME: nudch-photos
        WEBSERVICE_URL: http://webservice:4000
  tags:
    - docker

.use-app:
  variables:
    FF_NETWORK_PER_BUILD: 1
  services:
    - <<: *rabbitmq
    - <<: *mongodb
    - <<: *redis
    - name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      alias: webservice
      variables:
        NODE_ENV: test
  tags:
    - docker
