.use-dependencies:
  variables:
    FF_NETWORK_PER_BUILD: 1
  services:
    - &rabbitmq
      name: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/rabbitmq:3.13
      alias: rabbitmq
    - &mongodb
      name: $NUDCH_IMAGE_REGISTRY/nudchannel/database/devdb
      alias: mongodb
    - &redis
      name: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/redis:7-alpine
      alias: redis
  tags:
    - docker

.use-app:
  variables:
    FF_NETWORK_PER_BUILD: 1
  services:
    - <<: *rabbitmq
    - <<: *mongodb
    - <<: *redis
    - name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      alias: webservice
      variables:
        NODE_ENV: test
  tags:
    - docker
