test:unit:
  stage: test
  needs: []
  extends:
    - .node-test-coverage
    - .default-test-rules
  script: npm run test

test:it:
  stage: test
  needs: []
  extends:
    - .node-test-coverage
    - .use-dependencies
    - .default-test-rules
  script: npm run test:it

test:functional:
  stage: test
  needs: []
  extends:
    - .node-test-coverage
    - .default-test-rules
  script: npm run test:functional

test:e2e:
  stage: test
  needs:
    - build:image
  extends:
    - .node-test-coverage
    - .use-app
    - .default-test-rules
  variables:
    SERVER_URL: http://webservice:4000
  script:
    - npm run test:e2e
  after_script:
    - npm run test:cucumber:report
